services:
  web-pre:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ID: ${BUILD_ID:-local-dev}
    container_name: nemetz-de-web-pre
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - 'traefik.enable=true'

      # Middleware: Compression
      # Enable gzip/brotli compression for responses
      - 'traefik.http.middlewares.nemetz-pre-compress.compress=true'

      # Middleware: Security Headers
      # Enforce HTTPS redirects and set security-related HTTP headers
      - 'traefik.http.middlewares.nemetz-pre-security.headers.sslredirect=true'
      - 'traefik.http.middlewares.nemetz-pre-security.headers.stsseconds=31536000'
      - 'traefik.http.middlewares.nemetz-pre-security.headers.stsincludesubdomains=true'
      - 'traefik.http.middlewares.nemetz-pre-security.headers.stspreload=true'
      - 'traefik.http.middlewares.nemetz-pre-security.headers.contenttypenosniff=true'
      - 'traefik.http.middlewares.nemetz-pre-security.headers.browserxssfilter=true'

      # Middleware: Proxy Headers
      # Forward X-Forwarded-Proto to backend for proper scheme detection
      - 'traefik.http.middlewares.nemetz-pre-proxy-headers.headers.customrequestheaders.X-Forwarded-Proto=https'

      # Router: HTTPS (websecure entrypoint)
      # Matches all requests to pre.nemetz.de via TLS
      - 'traefik.http.routers.nemetz-de-pre.rule=Host(`pre.nemetz.de`)'
      - 'traefik.http.routers.nemetz-de-pre.entrypoints=websecure'
      - 'traefik.http.routers.nemetz-de-pre.tls.certresolver=cloudflare'
      - 'traefik.http.routers.nemetz-de-pre.middlewares=nemetz-pre-compress,nemetz-pre-security,nemetz-pre-proxy-headers@docker'
      - 'traefik.http.routers.nemetz-de-pre.service=nemetz-de-pre'

      # Router: HTTP (web entrypoint)
      # Redirects HTTP to HTTPS via security middleware
      - 'traefik.http.routers.nemetz-de-pre-http.rule=Host(`pre.nemetz.de`)'
      - 'traefik.http.routers.nemetz-de-pre-http.entrypoints=web'
      - 'traefik.http.routers.nemetz-de-pre-http.middlewares=nemetz-pre-security'
      - 'traefik.http.routers.nemetz-de-pre-http.service=nemetz-de-pre'

      # Service Definition
      - 'traefik.http.services.nemetz-de-pre.loadbalancer.server.port=3000'

networks:
  traefik-network:
    external: true
